import type { SourceDefinition } from '../types.ts';

export const KNOWN_SOURCES: SourceDefinition[] = [
  {
    name: 'cowork',
    displayName: 'Claude Cowork',
    defaultPath: '~/Library/Application Support/Claude/local-agent-mode-sessions',
    format: 'session-tree',
    description: 'Claude Cowork sessions with nested .claude/projects trees',
    enabled: true,
  },
  {
    name: 'opencode',
    displayName: 'OpenCode',
    defaultPath: '~/.local/share/opencode/opencode.db',
    format: 'sqlite',
    description: 'OpenCode SQLite database containing message data JSON blobs and parts',
    enabled: true,
  },
  {
    name: 'grok',
    displayName: 'Grok CLI',
    defaultPath: '~/.grok/sessions',
    format: 'session-tree',
    description: 'Grok CLI session trees',
    enabled: true,
  },
  {
    name: 'claude',
    displayName: 'Claude Code',
    defaultPath: '~/.claude/projects',
    format: 'jsonl',
    description: 'Claude Code streaming project JSONL files',
    enabled: true,
  },
  {
    name: 'antigravity',
    displayName: 'Gemini Antigravity',
    defaultPath: '~/.gemini/antigravity/conversations',
    format: 'sqlite',
    description: 'Antigravity conversation databases and turn logs',
    enabled: true,
  },
  {
    name: 'antigravity-brain',
    displayName: 'Antigravity Brain Artifacts',
    defaultPath: '~/.gemini/antigravity/brain',
    format: 'artifacts',
    description: 'Synthesized implementation plans, walkthroughs, and specs',
    enabled: true,
  },
  {
    name: 'codex',
    displayName: 'Codex CLI',
    defaultPath: '~/.codex/sessions',
    format: 'jsonl',
    description: 'Codex rollout JSONL sessions',
    enabled: true,
  },
  {
    name: 'qoder',
    displayName: 'Qoder',
    defaultPath: '~/.qoder/projects',
    format: 'session-tree',
    description: 'Qoder project session trees and shared client caches',
    enabled: true,
  },
  {
    name: 'gemini',
    displayName: 'Gemini CLI',
    defaultPath: '~/.gemini',
    format: 'session-tree',
    description: 'Gemini CLI local sessions and configurations',
    enabled: true,
  },
  {
    name: 'kimi-work',
    displayName: 'Kimi Work / Desktop',
    defaultPath: '~/Library/Application Support/kimi-desktop/daimon-share/daimon/runtime/kimi-code/home/sessions',
    format: 'session-tree',
    description: 'Kimi Code desktop runtime sessions',
    enabled: true,
  },
  {
    name: 'antigravity-cli',
    displayName: 'Antigravity CLI',
    defaultPath: '~/.gemini/antigravity-cli',
    format: 'sqlite',
    description: 'Antigravity CLI trajectory databases and protobufs',
    enabled: true,
  },
  {
    name: 'deepseek-harness',
    displayName: 'DeepSeek Harness',
    defaultPath: '~/.dsh/sessions',
    format: 'jsonl',
    description: 'DeepSeek Harness session logs',
    enabled: true,
  },
  {
    name: 'kilo',
    displayName: 'Kilo Code',
    defaultPath: '~/.local/share/kilo',
    format: 'session-tree',
    description: 'Kilo Code sessions and VS Code extension globalStorage',
    enabled: true,
  },
  {
    name: 'commandcode',
    displayName: 'Command Code',
    defaultPath: '~/.commandcode/projects',
    format: 'session-tree',
    description: 'Command Code project sessions',
    enabled: true,
  },
  {
    name: 'goose',
    displayName: 'Goose',
    defaultPath: '~/.local/share/goose/sessions',
    format: 'session-tree',
    description: 'Goose autonomous agent sessions',
    enabled: true,
  },
  {
    name: 'vscode-copilot',
    displayName: 'VS Code Copilot',
    defaultPath: '~/Library/Application Support/Code/User/workspaceStorage',
    format: 'session-tree',
    description: 'VS Code Copilot chat transcript storages',
    enabled: true,
  },
  {
    name: 'cursor',
    displayName: 'Cursor',
    defaultPath: '~/.cursor/projects',
    format: 'session-tree',
    description: 'Cursor IDE project workspaces and agent state',
    enabled: true,
  },
  {
    name: 'devin',
    displayName: 'Devin',
    defaultPath: '~/Library/Application Support/devin',
    format: 'session-tree',
    description: 'Devin desktop client sessions',
    enabled: true,
  },
  {
    name: 'pi',
    displayName: 'Pi',
    defaultPath: '~/.pi/agent/sessions',
    format: 'session-tree',
    description: 'Pi agent local sessions',
    enabled: true,
  },
  {
    name: 'warp',
    displayName: 'Warp',
    defaultPath: '~/Library/Group Containers/2BBY89MBSN.dev.warp/Library/Application Support/dev.warp.Warp-Stable',
    format: 'session-tree',
    description: 'Warp terminal sessions and AI commands',
    enabled: true,
  },
];
